In [1]:
import pandas as pd
df1 = pd.DataFrame({
    "city": ["Faisalabad","Lahore","Islamabad"],
    "temperature": [10,12,14],
})
df1

         city  temperature
0  Faisalabad           10
1      Lahore           12
2   Islamabad           14

In [2]:
df2 = pd.DataFrame({
    "city": ["Faisalabad","Lahore","Islamabad"],
    "humidity": [65,68,75],
})
df2

         city  humidity
0  Faisalabad        65
1      Lahore        68
2   Islamabad        75

In [3]:
df3 = pd.merge(df1, df2, on="city")
df3

         city  temperature  humidity
0  Faisalabad           10        65
1      Lahore           12        68
2   Islamabad           14        75

In [4]:
df1 = pd.DataFrame({
    "city": ["Multan","Peshawar","Gujranwala", "Sheikhupura"],
    "temperature": [21,14,35, 38],
})
df1

          city  temperature
0       Multan           21
1     Peshawar           14
2   Gujranwala           35
3  Sheikhupura           38

In [5]:
df2 = pd.DataFrame({
    "city": ["Multan","Peshawar","Jaranwala"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0     Multan        65
1   Peshawar        68
2  Jaranwala        71

In [6]:
df3=pd.merge(df1,df2,on="city",how="inner")
df3

       city  temperature  humidity
0    Multan           21        65
1  Peshawar           14        68

In [7]:
df3=pd.merge(df1,df2,on="city",how="outer")
df3

          city  temperature  humidity
0   Gujranwala         35.0       NaN
1    Jaranwala          NaN      71.0
2       Multan         21.0      65.0
3     Peshawar         14.0      68.0
4  Sheikhupura         38.0       NaN

In [8]:
df3=pd.merge(df1,df2,on="city",how="left")
df3

          city  temperature  humidity
0       Multan           21      65.0
1     Peshawar           14      68.0
2   Gujranwala           35       NaN
3  Sheikhupura           38       NaN

In [9]:
df3=pd.merge(df1,df2,on="city",how="right")
df3

        city  temperature  humidity
0     Multan         21.0        65
1   Peshawar         14.0        68
2  Jaranwala          NaN        71

In [10]:
df3=pd.merge(df1,df2,on="city",how="outer",indicator=True)
df3

          city  temperature  humidity      _merge
0   Gujranwala         35.0       NaN   left_only
1    Jaranwala          NaN      71.0  right_only
2       Multan         21.0      65.0        both
3     Peshawar         14.0      68.0        both
4  Sheikhupura         38.0       NaN   left_only

In [11]:
df1 = pd.DataFrame({
    "city": ["FSD","LHR","KHR","ISB"],
    "temperature": [21,14,35,38],
    "humidity": [65,68,71, 75]
})
df1

  city  temperature  humidity
0  FSD           21        65
1  LHR           14        68
2  KHR           35        71
3  ISB           38        75

In [12]:
df2 = pd.DataFrame({
    "city": ["FSD","LHR","RWL"],
    "temperature": [21,14,35],
    "humidity": [65,68,71]
})
df2

  city  temperature  humidity
0  FSD           21        65
1  LHR           14        68
2  RWL           35        71

In [13]:
df3= pd.merge(df1,df2,on="city",how="outer", suffixes=('_first','_second'))
df3

  city  temperature_first  humidity_first  temperature_second  humidity_second
0  FSD               21.0            65.0                21.0             65.0
1  ISB               38.0            75.0                 NaN              NaN
2  KHR               35.0            71.0                 NaN              NaN
3  LHR               14.0            68.0                14.0             68.0
4  RWL                NaN             NaN                35.0             71.0

In [14]:
df1 = pd.DataFrame({
    "city": ["FSD","LHR","ISB"],
    "temperature": [21,14,35],
})
df1.set_index('city',inplace=True)
df1

      temperature
city
FSD            21
LHR            14
ISB            35

In [15]:
df2 = pd.DataFrame({
    "city": ["LHR","FSD","ISB"],
    "humidity": [65,68,75],
})
df2.set_index('city',inplace=True)
df2

      humidity
city
LHR         65
FSD         68
ISB         75

In [16]:
df1.join(df2,lsuffix='_l', rsuffix='_r')

      temperature  humidity
city
FSD            21        68
LHR            14        65
ISB            35        75