In [121]:
import pandas as pd

# Path ko raw string (r"...") mein likhein taake backslashes kaam karein
file_path = r"C:\Users\Fine Traders\Downloads\Lab 4\pandas_dataframe_basics\pandas_dataframe_basics\weather_data.csv"

# CSV file read karein
df = pd.read_csv(file_path)

# Data check karne ke liye
print(df)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [122]:
df.shape # rows, columns = df.shape

(6, 4)

In [123]:
df.head() # df.head(3)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [124]:
df.tail() # df.tail(2)

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [125]:
df[1:3]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [126]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='str')

In [127]:
df['day']

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: str

In [128]:
df['temperature'].max()

np.int64(35)

In [129]:
df[df['temperature']>32]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [130]:
df['day'][df['temperature'] == df['temperature'].max()]

1    1/2/2017
Name: day, dtype: str

In [131]:
df[df['temperature'] == df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [132]:
df['event'].max()

'Sunny'

In [133]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [134]:
df.set_index('day')

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [135]:
df.set_index('day', inplace=True)

In [136]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='str', name='day')

In [137]:
df.loc['1/2/2017']

temperature       35
windspeed          7
event          Sunny
Name: 1/2/2017, dtype: object

In [138]:
df.reset_index(inplace=True)
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [139]:
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [140]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

In [141]:
import pandas as pd

pakistani_weather = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
pakistani_weather

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [142]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [143]:
df = pd.concat([pakistani_weather, us_weather], ignore_index=True)
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [144]:
df = pd.concat([pakistani_weather, us_weather], keys=["Pakistan", "US"])
df

                city  temperature  humidity
Pakistan 0   karachi           32        80
         1    lahore           45        60
         2  peshawar           30        78
US       0  new york           21        68
         1   chicago           14        65
         2   orlando           35        75

In [145]:
temperature_df = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0   karachi           32
1    lahore           45
2  peshawar           30

In [146]:
windspeed_df = pd.DataFrame({
    "city": ["lahore","karachi"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

      city  windspeed
1   lahore          7
0  karachi         12

In [147]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: str

In [148]:
df = pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
0   karachi           32  Humid
1    lahore           45    Dry
2  peshawar           30   Rain

In [149]:
import pandas as pd

file_path = r"C:\Users\Fine Traders\Downloads\Lab 4\pandas_group_by\pandas_group_by\weather_by_cities.csv"
df = pd.read_csv(file_path)

df

         day      city  temperature  windspeed   event
0   1/1/2024  new york           32          6    Rain
1   1/2/2024  new york           36          7   Sunny
2   1/3/2024  new york           28         12    Snow
3   1/4/2024  new york           33          7   Sunny
4   1/1/2024     dubai           90          5   Sunny
5   1/2/2024     dubai           85         12     Fog
6   1/3/2024     dubai           87         15     Fog
7   1/4/2024     dubai           92          5    Rain
8   1/1/2024     paris           45         20   Sunny
9   1/2/2024     paris           50         13  Cloudy
10  1/3/2024     paris           54          8  Cloudy
11  1/4/2024     paris           42         10  Cloudy

In [150]:
g = df.groupby("city")
g

In [151]:
for city, data in g:
    print("city:",city)
    print("\n")
    print("data:",data)

city: dubai


data:         day   city  temperature  windspeed  event
4  1/1/2024  dubai           90          5  Sunny
5  1/2/2024  dubai           85         12    Fog
6  1/3/2024  dubai           87         15    Fog
7  1/4/2024  dubai           92          5   Rain
city: new york


data:         day      city  temperature  windspeed  event
0  1/1/2024  new york           32          6   Rain
1  1/2/2024  new york           36          7  Sunny
2  1/3/2024  new york           28         12   Snow
3  1/4/2024  new york           33          7  Sunny
city: paris


data:          day   city  temperature  windspeed   event
8   1/1/2024  paris           45         20   Sunny
9   1/2/2024  paris           50         13  Cloudy
10  1/3/2024  paris           54          8  Cloudy
11  1/4/2024  paris           42         10  Cloudy

In [152]:
g.get_group('paris')

         day   city  temperature  windspeed   event
8   1/1/2024  paris           45         20   Sunny
9   1/2/2024  paris           50         13  Cloudy
10  1/3/2024  paris           54          8  Cloudy
11  1/4/2024  paris           42         10  Cloudy

In [153]:
g.min()

               day  temperature  windspeed   event
city
dubai     1/1/2024           85          5     Fog
new york  1/1/2024           28          6    Rain
paris     1/1/2024           42          8  Cloudy

In [154]:
g.mean(numeric_only=True)

          temperature  windspeed
city
dubai           88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [155]:
g.size()

city
dubai       4
new york    4
paris       4
dtype: int64

In [156]:
import pandas as pd
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [157]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [158]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [159]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [160]:
df3=pd.merge(df1,df2,on="city",how="inner")
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [161]:
df3=pd.merge(df1,df2,on="city",how="outer")
df3

        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  san diego          NaN      71.0

In [162]:
df3=pd.merge(df1,df2,on="city",how="left")
df3

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [163]:
df3=pd.merge(df1,df2,on="city",how="right")
df3

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

In [164]:
df3=pd.merge(df1,df2,on="city",how="outer",indicator=True)
df3

        city  temperature  humidity      _merge
0  baltimore         38.0       NaN   left_only
1    chicago         14.0      65.0        both
2   new york         21.0      68.0        both
3    orlando         35.0       NaN   left_only
4  san diego          NaN      71.0  right_only

In [165]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35,38],
    "humidity": [65,68,71, 75]
})
df1

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [166]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "temperature": [21,14,35],
    "humidity": [65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [167]:
df3= pd.merge(df1,df2,on="city",how="outer", suffixes=('_first','_second'))
df3

,city,temperature_first,humidity_first,temperature_second,humidity_second
0,baltimore,38.0,75.0,NaN,NaN
1,chicago,14.0,68.0,21.0,65.0
2,new york,21.0,65.0,14.0,68.0
3,orlando,35.0,71.0,NaN,NaN
4,san diego,NaN,NaN,35.0,71.0

In [168]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1.set_index('city',inplace=True)
df1

          temperature
city
new york           21
chicago            14
orlando            35

In [169]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2.set_index('city',inplace=True)
df2

          humidity
city
chicago         65
new york        68
orlando         75

In [170]:
import pandas as pd

file_path = r"C:\Users\Fine Traders\Downloads\Lab 4\pandas_group_by\pandas_group_by\weather_by_cities.csv"

df = pd.read_csv(file_path)

df

         day      city  temperature  windspeed   event
0   1/1/2024  new york           32          6    Rain
1   1/2/2024  new york           36          7   Sunny
2   1/3/2024  new york           28         12    Snow
3   1/4/2024  new york           33          7   Sunny
4   1/1/2024     dubai           90          5   Sunny
5   1/2/2024     dubai           85         12     Fog
6   1/3/2024     dubai           87         15     Fog
7   1/4/2024     dubai           92          5    Rain
8   1/1/2024     paris           45         20   Sunny
9   1/2/2024     paris           50         13  Cloudy
10  1/3/2024     paris           54          8  Cloudy
11  1/4/2024     paris           42         10  Cloudy

In [173]:
df.pivot(index='city',columns='day')

         temperature                            windspeed                    \
day         1/1/2024 1/2/2024 1/3/2024 1/4/2024  1/1/2024 1/2/2024 1/3/2024
city
dubai             90       85       87       92         5       12       15
new york          32       36       28       33         6        7       12
paris             45       50       54       42        20       13        8

                     event
day      1/4/2024 1/1/2024 1/2/2024 1/3/2024 1/4/2024
city
dubai           5    Sunny      Fog      Fog     Rain
new york        7     Rain    Sunny     Snow    Sunny
paris          10    Sunny   Cloudy   Cloudy   Cloudy

In [175]:
df.pivot(index='city', columns='day', values='temperature')

day       1/1/2024  1/2/2024  1/3/2024  1/4/2024
city
dubai           90        85        87        92
new york        32        36        28        33
paris           45        50        54        42

In [176]:
df.pivot(index='city', columns='day', values='windspeed')

day       1/1/2024  1/2/2024  1/3/2024  1/4/2024
city
dubai            5        12        15         5
new york         6         7        12         7
paris           20        13         8        10

In [177]:
df.pivot(index='day', columns='city')

         temperature                windspeed                 event           \
city           dubai new york paris     dubai new york paris  dubai new york
day
1/1/2024          90       32    45         5        6    20  Sunny     Rain
1/2/2024          85       36    50        12        7    13    Fog    Sunny
1/3/2024          87       28    54        15       12     8    Fog     Snow
1/4/2024          92       33    42         5        7    10   Rain    Sunny


city       paris
day
1/1/2024   Sunny
1/2/2024  Cloudy
1/3/2024  Cloudy
1/4/2024  Cloudy